/**************************************************************
 * 
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 * 
 *************************************************************/



/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openoffice_OpenOffice */

#ifndef _Included_ag_ion_bion_officelayer_NativeView
#define _Included_ag_ion_bion_officelayer_NativeView
#ifdef __cplusplus
extern "C" {
#endif
#undef ag_ion_bion_officelayer_NativeView_FOCUS_TRAVERSABLE_UNKNOWN
#define ag_ion_bion_officelayer_NativeView_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef ag_ion_bion_officelayer_NativeView_FOCUS_TRAVERSABLE_DEFAULT
#define ag_ion_bion_officelayer_NativeView_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef ag_ion_bion_officelayer_NativeView_FOCUS_TRAVERSABLE_SET
#define ag_ion_bion_officelayer_NativeView_FOCUS_TRAVERSABLE_SET 2L
#undef ag_ion_bion_officelayer_NativeView_TOP_ALIGNMENT
#define ag_ion_bion_officelayer_NativeView_TOP_ALIGNMENT 0.0f
#undef ag_ion_bion_officelayer_NativeView_CENTER_ALIGNMENT
#define ag_ion_bion_officelayer_NativeView_CENTER_ALIGNMENT 0.5f
#undef ag_ion_bion_officelayer_NativeView_BOTTOM_ALIGNMENT
#define ag_ion_bion_officelayer_NativeView_BOTTOM_ALIGNMENT 1.0f
#undef ag_ion_bion_officelayer_NativeView_LEFT_ALIGNMENT
#define ag_ion_bion_officelayer_NativeView_LEFT_ALIGNMENT 0.0f
#undef ag_ion_bion_officelayer_NativeView_RIGHT_ALIGNMENT
#define ag_ion_bion_officelayer_NativeView_RIGHT_ALIGNMENT 1.0f
#undef ag_ion_bion_officelayer_NativeView_serialVersionUID
#define ag_ion_bion_officelayer_NativeView_serialVersionUID -7644114512714619750LL
#undef ag_ion_bion_officelayer_NativeView_serialVersionUID
#define ag_ion_bion_officelayer_NativeView_serialVersionUID -2284879212465893870LL
#undef ag_ion_bion_officelayer_NativeView_serialVersionUID
#define ag_ion_bion_officelayer_NativeView_serialVersionUID 744155902373436284LL
/*
 * Class:     ag_ion_bion_officelayer_NativeView
 * Method:    getNativeWindowSystemType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ag_ion_bion_officelayer_NativeView_getNativeWindowSystemType
  (JNIEnv *, jobject);

/*
 * Class:     ag_ion_bion_officelayer_NativeView
 * Method:    getNativeWindow
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ag_ion_bion_officelayer_NativeView_getNativeWindow
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
